### ISSUE TITLE
不适配certbot2.4.0

### ISSUE THREAD

**Issue by jasonren0403** [tengattack/certbot-dns-dnspod#15]
在进行这两步后，certbot命令无法正常运行，显示报错 An unexpected error occurred:
TypeError: 'type' object is not iterable

sudo snap set certbot trust-plugin-with-root=ok
sudo snap connect certbot:plugin certbot-dns-dnspod

日志记录如下：

```
2023-03-25 20:34:39,417:DEBUG:urllib3.connectionpool:http://localhost:None "GET /v2/connections?snap=certbot&interface=content HTTP/1.1" 200 787
2023-03-25 20:34:39,739:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/snap/certbot/2836/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/snap/certbot/2836/lib/python3.8/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/snap/certbot/2836/lib/python3.8/site-packages/certbot/_internal/main.py", line 1835, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/snap/certbot/2836/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 192, in find_all
    cls._load_entry_point(entry_point, plugins)
  File "/snap/certbot/2836/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 199, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point)
  File "/snap/certbot/2836/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 40, in __init__
    self.plugin_cls: Type[interfaces.Plugin] = entry_point.load()
  File "/snap/certbot/2836/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in load
    return self.resolve()
  File "/snap/certbot/2836/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2474, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/snap/certbot-dns-dnspod/current/lib/python3.8/site-packages/certbot_dns_dnspod/dns_dnspod.py", line 21, in <module>
    class Authenticator(dns_common.DNSAuthenticator):
  File "/snap/certbot-dns-dnspod/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 1108, in __call__
    directlyProvides(ob, *self.interfaces)
  File "/snap/certbot-dns-dnspod/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 918, in directlyProvides
    interfaces = _normalizeargs(interfaces)
  File "/snap/certbot-dns-dnspod/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 1307, in _normalizeargs
    _normalizeargs(v, output)
  File "/snap/certbot-dns-dnspod/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 1306, in _normalizeargs
    for v in sequence:
TypeError: 'type' object is not iterable
2023-03-25 20:34:39,740:ERROR:certbot._internal.log:An unexpected error occurred:
2023-03-25 20:34:39,740:ERROR:certbot._internal.log:TypeError: 'type' object is not iterable
```

**Comment by jasonren0403** [comment]
走的是snap安装
certbot-dns-dnspod 0.24.1 from Eric Zhang (ericzhang456) installed

**Comment by LeenHawk** [comment]
+1

**Comment by lubobill1990** [comment]
+1

**Comment by lubobill1990** [comment]
You can install certbot and certbot-dns-dnspod using pip

https://certbot.eff.org/instructions?ws=nginx&os=pip

**Comment by Takunsyo** [comment]
Same issue here, working fine until Mar 25th 2023. it stops after then.

**Comment by tengattack** [comment]
zope 依赖已移除，可以尝试安装更新后再试试

cc @fengyunhe
