### ISSUE TITLE
遇到了错误，   File "/snap/certbot-dns-dnspod/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 1306, in _normalizeargs     for v in sequence: TypeError: 'type' object is not iterable

### ISSUE THREAD

**Issue by fengyunhe** [tengattack/certbot-dns-dnspod#17]
2024-02-28 08:57:13,452:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/snap/certbot/3643/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 191, in find_all
    cls._load_entry_point(entry_point, plugins)
  File "/snap/certbot/3643/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 203, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point)
  File "/snap/certbot/3643/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 42, in __init__
    self.plugin_cls: Type[interfaces.Plugin] = entry_point.load()
  File "/snap/certbot/3643/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 207, in load
    module = import_module(match.group('module'))
  File "/snap/certbot/3643/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/snap/certbot-dns-dnspod/current/lib/python3.8/site-packages/certbot_dns_dnspod/dns_dnspod.py", line 21, in <module>
    class Authenticator(dns_common.DNSAuthenticator):
  File "/snap/certbot-dns-dnspod/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 1108, in __call__
    directlyProvides(ob, *self.interfaces)
  File "/snap/certbot-dns-dnspod/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 918, in directlyProvides
    interfaces = _normalizeargs(interfaces)
  File "/snap/certbot-dns-dnspod/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 1307, in _normalizeargs
    _normalizeargs(v, output)
  File "/snap/certbot-dns-dnspod/current/lib/python3.8/site-packages/zope/interface/declarations.py", line 1306, in _normalizeargs
    for v in sequence:
TypeError: 'type' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/certbot/3643/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/snap/certbot/3643/lib/python3.8/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/snap/certbot/3643/lib/python3.8/site-packages/certbot/_internal/main.py", line 1866, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/snap/certbot/3643/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 193, in find_all
    raise errors.PluginError(
certbot.errors.PluginError: The 'certbot_dns_dnspod.dns_dnspod' plugin errored while loading: 'type' object is not iterable. You may need to remove or update this plugin. The Certbot log will contain the full error details and this should be reported to the plugin developer.
2024-02-28 08:57:13,452:ERROR:certbot._internal.log:The 'certbot_dns_dnspod.dns_dnspod' plugin errored while loading: 'type' object is not iterable. You may need to remove or update this plugin. The Certbot log will contain the full error details and this should be reported to the plugin developer.

**Comment by fengyunhe** [comment]
重复了 #15
