### ISSUE TITLE
certbot: error: unrecognized arguments: --dns-dnspod-credentials 

### ISSUE THREAD

**Issue by sbwfnhn** [tengattack/certbot-dns-dnspod#18]
```
[root@host-10 ~] python --version
Python 3.9.16

[root@host-10 ~]# cat /etc/redhat-release 
Rocky Linux release 9.2 (Blue Onyx)
```

```
[root@localhost ~]# certbot certonly -a dns-dnspod --dns-dnspod-credentials /etc/credentials.conf -d aa.chxxx.com
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-dnspod-credentials /etc/credentials.conf
```

需要创建python虚拟环境才能正确执行
```
#注意用root，非root下创建虚拟环境，没有权限执行certbot，使用了sudo命令提权至root账户，导制用户变更，python虚拟环境又失效。
mkdir /opt/python_env_certbot
cd /opt/python_env_certbot/
python3 -m venv certbotvenv
source certbotvenv/bin/activate
/opt/python_env_certbot/certbotvenv/bin/python3 -m pip install --upgrade pip
pip install git+https://github.com/tengattack/certbot-dns-dnspod.git

```

新申请
```
cd /opt/python_env_certbot
source certbotvenv/bin/activate
certbot certonly -a dns-dnspod \
    --dns-dnspod-credentials /etc/credentials.conf \
    -d s8.xfrx.ac.cn
```

续签
```
cd /opt/python_env_certbot
source certbotvenv/bin/activate
certbot renew --cert-name s8.xfrx.ac.cn
```

**Comment by sbwfnhn** [comment]
有如下报错
Hint: The Certificate Authority failed to verify the DNS TXT records created by --dns-dnspod. Ensure the above domains are hosted by this DNS provider, or try increasing --dns-dnspod-propagation-seconds (currently 30 seconds).

2024-04-08 21:23:40,066:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/python_env_certbot/certbotvenv/lib64/python3.9/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/python_env_certbot/certbotvenv/lib64/python3.9/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2024-04-08 21:23:40,066:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-04-08 21:23:40,066:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-04-08 21:23:40,068:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dnsapi.cn:443
2024-04-08 21:23:40,667:DEBUG:urllib3.connectionpool:https://dnsapi.cn:443 "POST /Domain.Info HTTP/1.1" 200 None
2024-04-08 21:23:40,671:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dnsapi.cn:443
2024-04-08 21:23:41,387:DEBUG:urllib3.connectionpool:https://dnsapi.cn:443 "POST /Domain.Info HTTP/1.1" 200 None
2024-04-08 21:23:41,392:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dnsapi.cn:443
2024-04-08 21:23:42,666:DEBUG:urllib3.connectionpool:https://dnsapi.cn:443 "POST /Record.List HTTP/1.1" 200 None
2024-04-08 21:23:42,669:DEBUG:lexicon._private.providers.dnspod:payload: {'status': {'code': '1', 'message': '操作已经成功完成', 'created_at': '2024-04-08 21:23:42'}, 'domain': {'id': '24547497', 'name': 'xhel.ac.cn', 'punycode': 'xhel.ac.cn', 'grade': 'DP_Free', 'owner': 'lihello1@vip.qq.com', 'ext_status': '', 'ttl': 600, 'min_ttl': 600, 'dnspod_ns': ['f1g1ns1.dnspod.net', 'f1g1ns2.dnspod.net'], 'status': 'enable', 'can_handle_at_ns': True}, 'info': {'sub_domains': '4', 'record_total': '4', 'records_num': '4'}, 'records': [{'id': '113381914', 'ttl': '86400', 'value': 'f1g1ns1.dnspod.net.', 'enabled': '1', 'status': 'enable', 'updated_on': '2016-01-02 03:42:58', 'record_type_v1': '1', 'name': '@', 'line': '默认', 'line_id': '0', 'type': 'NS', 'weight': None, 'monitor_status': '', 'remark': '', 'use_aqb': 'no', 'mx': '0', 'hold': 'hold'}, {'id': '113381916', 'ttl': '86400', 'value': 'f1g1ns2.dnspod.net.', 'enabled': '1', 'status': 'enable', 'updated_on': '2016-01-02 03:42:58', 'record_type_v1': '1', 'name': '@', 'line': '默认', 'line_id': '0', 'type': 'NS', 'weight': None, 'monitor_status': '', 'remark': '', 'use_aqb': 'no', 'mx': '0', 'hold': 'hold'}, {'id': '571734870', 'ttl': '600', 'value': '47.244.1.82', 'enabled': '1', 'status': 'enable', 'updated_on': '2020-04-13 13:20:32', 'record_type_v1': '1', 'name': 's2', 'line': '默认', 'line_id': '0', 'type': 'A', 'weight': None, 'monitor_status': '', 'remark': '', 'use_aqb': 'no', 'mx': '0'}, {'id': '1760266559', 'ttl': '600', 'value': 'hUZ3-jaaPN7EmTa4deCCWk918ReehE6EkE34FgpUC4c', 'enabled': '1', 'status': 'enable', 'updated_on': '2024-04-08 21:22:36', 'record_type_v1': '1', 'name': '_acme-challenge.s2', 'line': '默认', 'line_id': '0', 'type': 'TXT', 'weight': None, 'monitor_status': '', 'remark': '', 'use_aqb': 'no', 'mx': '0'}]}
2024-04-08 21:23:42,670:DEBUG:lexicon._private.providers.dnspod:list_records: [{'type': 'TXT', 'name': '_acme-challenge.s3.xhel.ac.cn', 'ttl': '600', 'content': 'hUZ3-jaaPN7EmTa4deCCWk918ReehE6EkE34FgpUC4c', 'id': '1760266559'}]
2024-04-08 21:23:42,670:DEBUG:lexicon._private.providers.dnspod:delete_records: ['1760266559']
2024-04-08 21:23:42,672:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dnsapi.cn:443
2024-04-08 21:23:44,333:DEBUG:urllib3.connectionpool:https://dnsapi.cn:443 "POST /Record.Remove HTTP/1.1" 200 None
2024-04-08 21:23:44,335:DEBUG:lexicon._private.providers.dnspod:delete_record: True
2024-04-08 21:23:44,336:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/python_env_certbot/certbotvenv/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/opt/python_env_certbot/certbotvenv/lib64/python3.9/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/python_env_certbot/certbotvenv/lib64/python3.9/site-packages/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
  File "/opt/python_env_certbot/certbotvenv/lib64/python3.9/site-packages/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/python_env_certbot/certbotvenv/lib64/python3.9/site-packages/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/python_env_certbot/certbotvenv/lib64/python3.9/site-packages/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/python_env_certbot/certbotvenv/lib64/python3.9/site-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/python_env_certbot/certbotvenv/lib64/python3.9/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/python_env_certbot/certbotvenv/lib64/python3.9/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/python_env_certbot/certbotvenv/lib64/python3.9/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2024-04-08 21:23:44,338:ERROR:certbot._internal.log:Some challenges have failed.

**Comment by lindaoling** [comment]
兄dei，解决了吗，我的证书过期了，也发现有这个问题

**Comment by Seunji** [comment]
按照op的方法，我走不通，还是报错:
```shell
(certbotvenv) root@tyy-dev:/opt/python_env_certbot# certbot certonly -a dns-dnspod --dns-dnspod-credentials /etc/nginx/dnspod.ini -d some.domain.here
PluginEntryPoint#certbot-dns-dnspod:dns-dnspod does not provide IPluginFactory, skipping
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --dns-dnspod-credentials /etc/nginx/dnspod.ini
```

- 更新
把 snap 安装的 dns-dnspod 插件卸载掉，就可以了
